stages:
  - stage_build
  - stage_test
  - stage_deploy_dev
  - stage_deploy_prd

variables:
  OWNER_NAME: "Leonid Badeev"
  CICD_VERSION: "v1.0"
  LOG_FILE_NAME: "log.txt"

# 0) Глобальный базовый образ для ВСЕХ job
image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

# 0.1) Дефолтные артефакты: сохраняем лог после КАЖДОЙ job
# Важно: в большинстве версий GitLab переменные внутри artifacts.paths НЕ разворачиваются.
# Поэтому используем прямой путь "log.txt".
default:
  artifacts:
    paths:
      - "log.txt"
    expire_in: "1 week"
    when: always

# 1) Build — создаёт log.txt
build_job:
  stage: stage_build
  script: |
    echo "---Build Started---"        | tee    "${LOG_FILE_NAME}"
    echo "Owner:  ${OWNER_NAME}"      | tee -a "${LOG_FILE_NAME}"
    echo "Ver:    ${CICD_VERSION}"    | tee -a "${LOG_FILE_NAME}"
    echo "Building..."                | tee -a "${LOG_FILE_NAME}"
    echo "---Build Completed---"      | tee -a "${LOG_FILE_NAME}"
    echo "=== log after Build ==="
    wc -c "${LOG_FILE_NAME}" | awk '{print "size(bytes):",$1}'
    cat -n "${LOG_FILE_NAME}"
