name: CI Pipeline

on: # Определяем, когда запускать workflow
  push:
    branches: [ main ]

jobs: # Обязательный корневой элемент для GitHub Actions
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.328.0
      
      - name: Run script
        run: |
          echo "Repo: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Author: ${{ github.actor }}"
          date
          printf "Hello from GitHub Actions\n" > hello.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-file
          path: hello.txt
          retention-days: 1
