jobs:
  stages:          # List of stages for jobs, and their order of execution
  - demo

  hello-ci:
    stage: demo
    image: alpine:3.20
    script: |
      - echo "Repo :    ${CI_PROJECT_PATH}"
      - echo "Branch :  ${CI_COMMIT_REF_NAME}"
      - echo "Commit :  ${CI_COMMIT_SHORT_SHA}"
      - echo "By :      ${GITLAB_USER_LOGIN}"  # Исправлено имя переменной
      - date
      - printf "Hello from gitlab ci\n" > hello.txt
      artifacts:
        expire_in: 1 day
